
default: &default
  adapter: postgresql
  database: RBP
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  password: VP98RQb9

development:
  adapter: postgresql
  database: RBP
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  password: VP98RQb9

production:
  adapter: postgresql
  database: RBP
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  password: VP98RQb9
